
import './globals.css'

import toast, { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Banquet-Bazzar-App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (

    <html lang="en">
      <body>
        {children}       

        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" rel="stylesheet" type="text/css" />
        <div><Toaster /></div>
      </body>
    </html>
  )
}
